set_project("verilator_utils")
set_languages("c++latest")
set_warnings("allextra")
add_requires("doctest", "verilator")
add_requires("zlib")
add_packages("doctest", "verilator")
set_exceptions("cxx")
add_cxxflags("-Wno-deprecated-missing-comma-variadic-parameter", "-Wno-sign-compare", "-Wno-unused-parameter")
set_policy("build.c++.modules.hide_dependencies", true)
set_defaultmode("release")

option("use_sanitizer")
    set_default(false)
    set_description("Enable sanitizer for unit tests")
option_end()

rule("verilator_include")
    after_load(function (target)
        target:add("includedirs", path.join(target:pkgenvs()["VERILATOR_ROOT"], "include"), {public = true})
    end)
rule_end()
add_rules("verilator_include")

includes("*/xmake.lua")
